"""hopeitdoesntbreak

Revision ID: 3d3e7f6488b2
Revises: 
Create Date: 2022-10-18 18:00:47.063404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3e7f6488b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_username'), 'login', ['username'], unique=True)
    op.create_table('user',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('github', sa.String(length=128), nullable=True),
    sa.Column('skills', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['login.id'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_login_username'), table_name='login')
    op.drop_table('login')
    # ### end Alembic commands ###
