"""user table

Revision ID: 96452e2f1255
Revises: bbb4580fffa0
Create Date: 2022-10-18 02:13:23.425495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96452e2f1255'
down_revision = 'bbb4580fffa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('github', sa.String(length=128), nullable=True),
    sa.Column('skills', sa.String(length=1000), nullable=True),
    sa.Column('interests', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['login_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
