"""changed

Revision ID: f66fedbbe6a3
Revises: 96452e2f1255
Create Date: 2022-10-18 02:22:35.189722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66fedbbe6a3'
down_revision = '96452e2f1255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_username'), 'login', ['username'], unique=True)
    op.drop_index('ix_login_table_username', table_name='login_table')
    op.drop_table('login_table')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'login', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'login_table', ['user_id'], ['id'])
    op.create_table('login_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_table_username', 'login_table', ['username'], unique=False)
    op.drop_index(op.f('ix_login_username'), table_name='login')
    op.drop_table('login')
    # ### end Alembic commands ###
